config/routes.rb
Rails.application.routes.draw do
  delete "users/sign_out"
  devise_for :users
  resources :dishes
  resources :reviews
  resources :restaurants
  namespace :admin do
    resources :restaurants

  end
  root "restaurants#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dish.rb
class Dish < ApplicationRecord
    belongs_to :restaurant
    has_many :reviews , as: :reviewable
  end
  

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :dishes
    has_many :reviews , as: :reviewable

    
    def showdishes
        self.dishes.each do |dish|
            dish.menu 
            dish.price
        end
    end
    paginates_per 5

end

    
   

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :reviewable , polymorphic: true 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < ApplicationController
    before_action :set_restaurant , only: [:edit, :update, :show, :destory]
    def index
      @restaurants = Restaurant.all
    end
  
    def new
      @restaurant = Restaurant.new
    end
  
    def create
      @restaurant = Restaurant.new(restaurant_params)
      if @restaurant.save
        redirect_to admin_restaurants_path
      else 
        render :new
      end
    end
    def show
     
    end
    def dishes_params
      params.require(:resto).permit(:name)
    end
  
    def edit
    end
    def update
      if @restaurant.update(restaurant_params)
        redirect_to admin_restaurants_path(@restaurant)
      else
        render :edit
      end
    end
    
  
    def destroy
      @restaurant.destroy
      redirect_to admin_restaurants_path
    end
    private
    def restaurant_params
      params.require(:restaurant).permit(:name , :place)
    end
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end 
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish , only: [:show , :edit , :update , :destroy]
  def index
    @dishes = Dish.all
  end

  def new
    @dish = Dish.new
  end

  def create
    @dish = Dish.new(dish_params)
    if @dish.save 
      redirect_to dishes_path
    else
      render :show
    end
  end

  def show
  end

  def edit

  end

  def update
    @dish.update(dish_params)
    redirect_to dishes_path
  end

  def destroy
    @dish.destroy
    redirect_to dishes_path
  end
  def dish_params
    params.require(:dish).permit(:menu , :price , :restaurant_id  ) 
  end
  def set_dish
    @dish = Dish.find(params[:id])
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant , only: [:edit, :update, :show, :destory]
  before_action :authenticate_user!  , except: [:index , :show]
  def index
    @q = Restaurant.ransack(params[:q])
    @restaurants = @q.result(distinct: true).page(params[:page])
    # @restaurants = Restaurant.all.page(params[:page])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else 
      render :new
    end
  end
  def show
   
  end
  def dishes_params
    params.require(:resto).permit(:name)
  end

  def edit
  end
  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurants_path(@restaurant)
    else
      render :edit
    end
  end
  
  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end
  private
  def restaurant_params
    params.require(:restaurant).permit(:name , :place)
  end
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
  
   
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review , only: [:show , :edit , :update , :destroy]
  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    if @review.save 
      debugger
      redirect_to reviews_path
    else
      render :show
    end
  end

  def show
  end

  def edit

  end

  def update
    @review.update(review_params)
    redirect_to reviews_path
  end

  def destroy
    @review.destroy
  end
  def review_params
    params.require(:review).permit(:comment, :rating, :reviewable_id )
  end
  def set_review
    @review = Review.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/restaurants/edit.html.erb
<h1>Restaurants edit</h1>



<%= form_with model: @restaurant do |form| %>
<div class = "col-lg-8">
<%= form.label :name %><br>
<%= form.text_field :name %> <br>
</div>
<%= form.label :place %> <br>
<%= form.text_field :place %><br>

<%= form.submit %>
<% end %>






<%# <%= render 'createdish' %> 

app/views/admin/restaurants/index.html.erb
<h1> Restaurants info page </h1>

<%= link_to "create" ,  new_restaurant_path %>


<table>

<tr><th> Name  </th>
<th> Address  </th>
<th>  Action </th>
<th>  Action </th>
<th>  Action </th></tr>

<tr> <% @restaurants.each do |restaurant| %>
<td> <%= restaurant.name %> </td>
     <td> <%= restaurant.place %> </td> 
     <%# <td> <%= restaurant.greeting %> </td>  
     
     <td> <%= link_to "edit" , edit_restaurant_path(restaurant) %> </td>
      <td> <%= link_to "show" , restaurant %> </td>
      <td> <%= button_to 'delete' , restaurant ,method: :delete %> </td>
     </tr>
      <% end %>


</table>















 

app/views/admin/restaurants/new.html.erb
<h1>Restaurants new</h1>



<%= form_with model: @restaurant do |form| %>

<%= form.label :name %><br>
<%= form.text_field :name %> <br>

<%= form.label :place %><br>
<%= form.text_field :place %> <br>





<%= form.submit %>
<% end %>

app/views/admin/restaurants/show.html.erb
<h1> Restaurant </h1>


<p> <strong> Restaurant Name :</strong> <%= @restaurant.name %> </p>
<p> <strong> Restaurant Address :</strong> <%= @restaurant.place %> </p>

<p> <%= link_to "edit The Restaurant " , edit_restaurant_path(@restaurant) %>
<p> <%= link_to "Delete The Restaurant " , @restaurant , method: :delete %>


  <% @restaurant.dishes.each do |dish| %>

<p> <%= link_to dish.name , dish_path(dish) %> </p>

<% end %>

app/views/dishes/edit.html.erb
<h2>    Dish Edit </h2>

<%= form_with model: @dish do |form| %>

<%= form.label :Dishname  %> <br>
<%= form.text_field :menu %><br>

<%= form.label :Dish_Price %> <br>
<%= form.text_field :price %><br>

 <p>Restaurant: <%= form.select :restaurant_id, Restaurant.all.map { |restaurant| [ restaurant.name,restaurant.id ] } %></p>


<%= form.submit %>
<% end %>

<br>
<%= link_to "Back" , dishes_path , class:"btn btn-secondary btn-sm" %>

app/views/dishes/index.html.erb
<h1> dishs info page </h1>

<%= link_to "create" ,  new_dish_path %>

<table class="table table-hover">
    <thead>
      <tr>
        <th>Dishname</th>
        <th>Price</th>
        <%# <th>Action</th> %>
        <th>Action</th>
        <th>Action</th>
        <th>Action</th>
      </tr>
    </thead>
    <% @dishes.each do |dish| %>
    <tbody>
      <tr>
        <td><%= dish.menu %></td>
        <td><%= dish.price %> </td>
        <%# <td><%= dish.restaurant_id %></td>  
        <td><%= link_to "edit" , edit_dish_path(dish),class:"btn btn-warning"  %></td>
        <td><%= link_to "show" , dish ,class:"btn btn-primary" %></td>
        <td><%= button_to 'delete' , dish ,method: :delete ,class:"btn btn-danger" %></td>
      </tr>
      
    </tbody>
    <% end %>
  </table>















 

app/views/dishes/new.html.erb
<h2>    Dish </h2>

<%= form_with model: @dish do |form| %>

<%= form.label :Dishname  %> <br>
<%= form.text_field :menu %><br>

<%= form.label :DishPrice %> <br>
<%= form.text_field :price %><br>


 <p>Restaurant: <%= form.select :restaurant_id, Restaurant.all.map { |restaurant| [ restaurant.name,restaurant.id ] } %></p>

<%= form.submit %>
<% end %>

<br>
<%= link_to "Back" , dishes_path , class:"btn btn-secondary btn-sm" %>

app/views/dishes/show.html.erb
<h1> Dish </h1>


<p> <strong> Dish Name :</strong> <%= @dish.menu %> </p>
<p> <strong> Dish Price :</strong> <%= @dish.price %> </p>
<p> <strong> Restaurant Id :</strong> <%= @dish.restaurant_id %> </p>

<br>
<%= link_to "Back" , dishes_path , class:"btn btn-secondary btn-sm" %>
<%= button_to 'delete' , @dish ,method: :delete ,class:"btn btn-outline-danger btn-sm" %>


  <h1> Reviews </h1>
  <table  class="table table-dark table-hover">
    <thead>
      <tr>
        <th> Comment</th>
        <th>Rating</th>
      </tr>
    </thead>
    <% @dish.reviews.each do |review| %>
    <tbody>
      <tr>
        <td> <%= review.comment %></td>
        <td><%= review.rating %></td>
        </tr>
      </tbody>
      <% end %>
  </table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    
  </head>

  <body>
  <div class= "container" >
 
  <%= render "shared/header" %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
   </div>
  </body>
</html>

app/views/restaurants/edit.html.erb
<h1>Restaurants edit</h1>



<%= form_with model: @restaurant do |form| %>
<div class = "col-lg-8">
<%= form.label :name %><br>
<%= form.text_field :name %> <br>
</div>
<%= form.label :place %> <br>
<%= form.text_field :place %><br>

<%= form.submit %>
<% end %>


<br>
<%= link_to "Back" , restaurants_path , class:"btn btn-secondary btn-sm" %>




<%# <%= render 'createdish' %> 

app/views/restaurants/index.html.erb
<h1> Restaurants info page </h1>

     


<%= link_to "create" ,  new_restaurant_path %>

  </table>
        <table class="table table-hover">
    <thead>
      <tr>
        <th>Restaurant</th>
        <th>Place</th>
        <th>Action</th>
        <th>Action</th>
        <th>Action</th>
      </tr>
    </thead>
    <% @restaurants.each do |restaurant| %>
    <tbody>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.place %></td>
        <td><%= link_to "show" , restaurant  ,class:"btn btn-primary" %> </td>
        <td><%= link_to "edit" , edit_restaurant_path(restaurant) ,class:"btn btn-warning" %></td>
        <td><%= button_to 'delete' , restaurant ,method: :delete ,class:"btn btn-danger" %></td>
      </tr>
    </tbody>
    <% end %>
  </table>
<%= paginate @restaurants %>














 

app/views/restaurants/new.html.erb
<h1>Restaurants new</h1>



<%= form_with model: @restaurant do |form| %>

<%= form.label :name %><br>
<%= form.text_field :name %> <br>

<%= form.label :place %><br>
<%= form.text_field :place %> <br>

<%= form.submit %>
<% end %>

<br>
<%= link_to "Back" , restaurants_path , class:"btn btn-secondary btn-sm" %>

app/views/restaurants/show.html.erb
<h1> Restaurant </h1>


<p> <strong> Restaurant Name :</strong> <%= @restaurant.name %> </p>
<p> <strong> Restaurant Address :</strong> <%= @restaurant.place %> </p>
 
<br>
<%= link_to "Back" , restaurants_path , class:"btn btn-secondary btn-sm" %>

  <h1> Dishes </h1>
 <table  class="table table-dark table-hover">
    <thead>
      <tr>
        <th> Menu</th>
        <th>price</th>
      </tr>
    </thead>
    <% @restaurant.dishes.each do |dish| %>
    <tbody>
      <tr>
        <td> <%= dish.menu %></td>
        <td><%= dish.price %></td>
        </tr>
      </tbody>
      <% end %>
  </table>

  <h1> Reviews </h1>
  <table  class="table table-dark table-hover">
    <thead>
      <tr>
        <th> Menu</th>
        <th>price</th>
      </tr>
    </thead>
    <% @restaurant.reviews.each do |review| %>
    <tbody>
      <tr>
        <td> <%= review.comment %></td>
        <td><%= review.rating %></td>
        </tr>
      </tbody>
      <% end %>
  </table>

app/views/reviews/edit.html.erb
<h2>     Edit  Reviews</h2>

<%= form_with model: @review do |form| %>

<%= form.label :Comment   %> <br>
<%= form.text_field :comment %><br>

<%= form.label :Rating %> <br>
<%= form.text_field :rating %><br>

<p>Restaurant: <%= form.select :restaurant_id, Restaurant.all.map { |restaurant| [ restaurant.name,restaurant.id ] } %></p>

<p>Dish: <%= form.select :reviewable_id, Dish.all.map { |dish| [dish.menu,dish.id ] } %></p>

<%= form.submit %>
<% end %>

<br>
<%= link_to "Back" , reviews_path , class:"btn btn-secondary btn-sm" %>

app/views/reviews/index.html.erb
<h1> All Reviews </h1>

<%= link_to "create" ,  new_review_path %>

<table class="table table-hover">
    <thead>
      <tr>
        <th>Comment</th>
        <th>Rating</th>
        <%# <th> ID </th> %>
        <th>Action</th>
        <th>Action</th>
        <th>Action</th>
      </tr>
    </thead>
     <% @reviews.each do |review| %>
    <tbody>
      <tr>
        <td><%= review.comment %></td>
        <td><%= review.rating %></td>
        
        <td><%= link_to "show" , review ,class:"btn btn-primary" %></td>
        <td><%= link_to "edit" , edit_review_path(review), class:"btn btn-warning" %></td>
        <td><%= button_to 'delete' , review ,method: :delete ,class:"btn btn-danger" %></td>
      </tr>
    </tbody>
    <% end %>
  </table>















 

app/views/reviews/new.html.erb
<h2>     New Reviews </h2>

<%= form_with model: @review do |form| %>

<%= form.label :Comment   %> <br>
<%= form.text_field :comment %><br>

<%= form.label :Rating %> <br>
<%= form.text_field :rating %><br>
<p>Restaurant: <%= form.select :reviewable , Restaurant.all.map { |restaurant| [ restaurant.name,restaurant.id ] } %></p>

<%# <p>Dish: <%= form.select :reviewable_id, Dish.all.map { |dish| [dish.menu,dish.id ] } %></p>


<%= form.submit %>
<% end %>

<br>
<%= link_to "Back" , reviews_path , class:"btn btn-secondary btn-sm" %>

app/views/reviews/show.html.erb
<h1> Reviews  </h1>


<p> <strong> Comment :</strong> <%= @review.comment %> </p>
<p> <strong> Rating :</strong> <%= @review.rating %> </p>
<%# <p> <strong> Restaurant Id :</strong> <%= @review.reviewable_id %> </p> 


<br>
<%= link_to "Back" , reviews_path , class:"btn btn-secondary btn-sm" %>

 

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Restaurants</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <% if user_signed_in? %>
              <li class="nav-item">
          <%=  link_to "signout " , destroy_user_session_path , :method => :delete %>
       </li>
              
        <% else %>
              <li class="nav-item">
                 <a class="nav-link" href=<%= new_user_session_path %>>Sign In</a>
              </li>
        <% end %>

        <li class="nav-item">
          <a class="nav-link" href=<%= new_user_registration_path %>>Sign Up</a>
       </li>
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="Availble Resources">
            <li><a class="dropdown-item" href=<%= dishes_path %>>Dishes</a></li>
            <li><a class="dropdown-item" href=<%= reviews_path %>>Reviews</a></li>
            <li><a class="dropdown-item" href=<%= restaurants_path %>>Restaurants</a></li>
            
          </ul>
        </li>
        
      </ul>
   
    </div>
  </div>
</nav>

 